# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Text A Coder Blog
email: nick@textacoder.com
description: > # this means to ignore newlines until "baseurl:"
  Learn how to become a freelance developer and hire other
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.textacoder.com" # the base hostname & protocol for your site
twitter_username: textacoder
permalink: /:title
paginate: 10
paginate_path: "blog/page/:num"
paginate_post_type: blog
gems:
  - jekyll-sitemap
# Build settings
markdown: kramdown
